# build environment
FROM node:latest as builder
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
ADD package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install react-scripts@1.1.0 -g --silent
ADD . /usr/src/app
RUN npm run build

# production environment
FROM nginx:1.13.5-alpine
RUN mkdir -p /var/www/
COPY --from=builder /usr/src/app/build /var/www/ophelia
COPY client_nginx_config /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]